- type: entity
  parent: [BaseItem, BaseFoldable]
  id: BaseCardFlippable
  abstract: true
  components:
  - type: Appearance
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: fold-flip-verb
    foldVerbText: fold-flip-verb
  - type: Sprite
    layers:
    - state: [ icon, inhand-left, inhand-right ]
      map: [ "unfoldedLayer" ]
      visible: true
    - state: - state: [ icon_flipped, inhand-left_flipped, inhand-right_flipped ]
      map: ["foldedLayer"]
      visible: false

- type: entity
  parent: BaseCardFlippable
  id: BaseCardFlipped
  abstract: true
  components:
  - type: Foldable
    folded: true
  - type: Item
    heldPrefix: flipped
  - type: Sprite
    layers:
    - state: [ icon, inhand-left, inhand-right ]
      map: [ "unfoldedLayer" ]
      visible: false
    - state: [ icon_flipped, inhand-left_flipped, inhand-right_flipped ]
      map: ["foldedLayer"]
      visible: true
